### ISSUE TITLE
Serenity Code Generator gives error - System.InvalidOperationException: KDiff3, verilen ...

### ISSUE THREAD

**Issue by sonnyramsayci** [volkanceylan/Serenity-Tutorials#1]
When I run Serenity Code Generator I get an error - 

System.InvalidOperationException: KDiff3, verilen " konumunda bulunamadi! at Serenity.CodeGenerator.CodeFileHelper.MergeChanges(String backup, String file) at Serenity.CodeGenerator.EntityCodeGenerator.CreateNewSiteWebFile(String code, String relativeFile) at Serenity.CodeGenerator.EntityCodeGenerator.GenerateRow() at Serenity.CodeGenerator.EntityCodeGenerator.Run() at Serenity.CodeGenerator.MainWindow.GenerateCodes_Click(Object sender, RoutedEventArgs e)

**Comment by sonnyramsayci** [comment]
Ok, I just needed to install KDiff3, and in my case (since I'm running 32-bit Windows) update the KDiff3Path in Serenity.CodeGenerator.config to "C:\\Program Files\\KDiff3\\kdiff3.exe".

**Comment by volkanceylan** [comment]
It tries to run KDiff when you generated code for entity and existing code will be overriden to let you merge changes, but I should translate message, and make it a bit more descriptive, and uhm document it :)
