### ISSUE TITLE
BaseModel

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity-Tutorials#10]
Volkan bey,

Veri tabanında Product (abstract) diye bir tablomuz olsun ve bu tablo dan Hotel ve Flight türemiş olsun,
HotelRow : ProductRow
FlightRow : ProductRow
Bu tarz bir model mimarisi için nasıl bir yöntem izlenilmelidir, Hotel=>Save için önce Product tablosuna kayıt eklenmeli ve ilgili ID ile Hodel tablosu kayıt edilmelidir. Yani temelde 1 den fazla tablonun tek bir entity olarak kullanımı durumu söz konusu olacaktır. Mevcut sistem içerisinde bunu durumu karşılayabilir miyiz.

Sanırım mevcut sistem Interface ler üzerinden ilerlemek üzerine tasarlanmış. HotelRow ve FlightRow yine Row dan türeyecek içerisinde Product öğeride yer alacak ve IProduct gibi bir Interface üzerinden Repository üzerinde önce Product üzerindeki işlem yapılarak sonra subEntity üzerindeki işlem yapılmaya çalışacak gibi. Ama bu durum kodlama maliyeti doğurmakta.

Konu ile ilgili sizin düşünceniz nedir?

**Comment by volkanceylan** [comment]
LoggingRow yapısına benzer şekilde base class kullanabilirsiniz. Ancak iki tabloya otomatik kayıt atmak gibi bir destek yok. HotelRepository deki BeforeSave vs. gibi methodları override edip, HotelRow u ProductRepository ye yollayabilirsiniz.

**Comment by neonemivar** [comment]
Bu durum kodlama maliyeti açısından biraz zahmetli ama sanırım yapacak bir şey yok.
Çoğu zaman bir tabloyu birden fazla entity ve birden fazla tabloyu da bir entity olarak kullanmak gerekiyor...
