### ISSUE TITLE
Multi Tenancy - problem with TypeScript

### ISSUE THREAD

**Issue by KrzysiekL** [volkanceylan/Serenity-Tutorials#11]
I have problem in class UserDialog - Method GetPropertyItems (Point 3.2.5 in Serenity Developer Guide). Currently this class has ceased to be used (I suppose) - it has replaced by userDialog.ts. 
Could you help me to correctlly move this change?

**Comment by volkanceylan** [comment]
Method should still be there to be overridden in C# or TS

**Comment by KrzysiekL** [comment]
Thanks, In the new version of the manual is an example of typescript for this point.
