### ISSUE TITLE
Function vaye Procedure nasıl çağıra biliriz.

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity-Tutorials#12]
Volkan bey,

Örneklere baktım ancak bir Function veya Procedure ü nasıl çağırmak gerektiğine dair bir tanım göremedim. Ben   var query = new SqlQuery();   ile çağırmak gerektiğini düşündüm ancak, bu yapı sanırım direkt select query oluşturmak için.

Tek bir string result dönen bir function var ve tek bir parametre almakta, sizce nasıl bir yöntem ile ilgili veriyi çekebilirim, saygılarımla.

**Comment by volkanceylan** [comment]
Normal Dapper ile çağırabilirsiniz

connection.Query("call my proc here", new { param1: ..., param2:  })

**Comment by neonemivar** [comment]
Volkan bey

Hata almaktayım, detaylar aşağıda yer aldığı gibi, gözümden kaçan bir şey var mıdır,

Function: (test edildi parametre ile çalışmakta)
ALTER Function [dbo].[GetFullFileList]
(
	@surveyId int
)
...

Code:
connection.Query<string>("GetFullFileList", new { surveyId = surveyId.Value }).First();

Error:
Procedure or function 'GetFullFileList' expects parameter '@surveyId', which was not supplied.

**Comment by neonemivar** [comment]
`ALTER Function [dbo].[GetFullFileList]
(
	@surveyId int
)`

`connection.Query<string>("GetFullFileList", new { surveyId = surveyId.Value }).First();`

**Comment by neonemivar** [comment]
Volkan bey,

Sanırım sorun, 'private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> { ... }` override ettiğim `protected override void OnReturn() { ... }` method içerisinde yer alan this.Row.Id doldurulmamasından kaynaklı.

**Comment by volkanceylan** [comment]
connection.Query("GetFullFileList(@surveyId)", new { surveyId = surveyId.Value }).First();

**Comment by neonemivar** [comment]
`connection.Query<string>("Select GetFullFileList(@surveyId)", new { surveyId = surveyId.Value }).First();`
Function olduğu için başına Select koymak gerekiyormuş. Sıkıntısız çalışıyor, destek için teşekkür ederim,
