### ISSUE TITLE
Just getting started with serenitybut it looks great

### ISSUE THREAD

**Issue by billjray** [volkanceylan/Serenity-Tutorials#2]

**Comment by billjray** [comment]
Any guidance for multiple lookup items on a single file

**Comment by volkanceylan** [comment]
You mean multiple lookup lists in one table? Or multiple selection, like tagging?

**Comment by billjray** [comment]
exactly. I tried multiple lookup tags and what seemed to be reasonable complex concatenations but no luck.  I'm looking at a table that has 2 foreign keys and 2 external tables for lookups

**Comment by volkanceylan** [comment]
Override a Select2 based editor, add IStringValue interface and apply following code:

```cs
        protected override Select2Options GetSelect2Options()
        {
            var opt = base.GetSelect2Options();
            opt.Multiple = true;
            return opt;
        }

        string IStringValue.Value
        {
            get
            {
                return (this.element.Select2Get("val") as string[]).Join(",");
            }
            set
            {
                base.Value = value == null ? null : value.Split(',').As<string>();
            }
        }
```

This will give you multiple selection with a value of comma separated string. But i'm not if this is what you need.

**Comment by billjray** [comment]
No good, good code but I'm looking to do lookups on 2 different tables

**Comment by volkanceylan** [comment]
You mean join or two separate lookup editors like cascaded?

**Comment by billjray** [comment]
2 separate and independent lookup editors, with 2 foreign keys, but not cascading from 2 other tables

**Comment by billjray** [comment]
![example](https://cloud.githubusercontent.com/assets/11316992/11532191/d8bdf108-98c7-11e5-8dfc-c6ca3419fa7a.gif)

**Comment by volkanceylan** [comment]
Why dont you add two fields and two editors than i dont understand

**Comment by rbianco3** [comment]
the library would be nice if it worked, it just isn't worth the effort. Better instruction guides that work would help as well too bad, everything in .NET either sucks balls or is nice but as solid as a house of cards.

**Comment by volkanceylan** [comment]
if you had a problem, you should tell about what and where. any platform, any library might have issues, just check any repo in github. with your logic they all sucks, and sorry there is no library for you among a million here.
