### ISSUE TITLE
LookupEditorBase kullanımı

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity-Tutorials#3]
Merhaba,

Form üzerinde 2 adet LookupEditor var ve birci değiştiğinde ikincinin Items ının değişmesini nasıl sağlayabilirim. Northwind içerisinde filtre için yapılmış olanları kullanmayı denedim, ancak sanırım Items değeri değişiyor ancak form u Refrehs edemediğim için yine liste full geliyor, aşağıda örnek code yer almakta, saygılarımla.

AnswerValueEditor içerisinde yer alan QuestionBankId ı nerede set etmeliyim, entity içerisinden otomatik aldırma imkanı var mıdır. Sonuç olarak ilgili soru için tanımlanmış soru setinden birini seçtirmeye çalışıyorum. Soru değişir ise cevap seti de değişmeli, direk bir relation yok...

    public class AnswerValueEditor : LookupEditorBase<QuestionOptionRow>
    {
        private CascadedWidgetLink<LookupEditor> questionBankLink;

        public AnswerValueEditor(jQueryObject container)
            : base(container)
        {
            questionBankLink = new CascadedWidgetLink<LookupEditor>(this, p => this.QuestionBankId = int.Parse(p.Value));
        }

        protected override string GetLookupKey()
        {
            return QuestionOptionRow.LookupKey;
        }

        protected override IEnumerable<QuestionOptionRow> GetItems(Lookup<QuestionOptionRow> lookup)
        {
            return base.GetItems(lookup).Where(x => x.QuestionBankId == QuestionBankId);
        }

        [Option]
        public string QuestionBankEditorId
        {
            get { return questionBankLink.ParentID; }
            set { questionBankLink.ParentID = value; }
        }

        private int? questionBankId;

        [Option]
        public int? QuestionBankId
        {
            get { return questionBankId; }
            set
            {
                if (questionBankId != value)
                {
                    questionBankId = value;
                    Value = null;
                    UpdateItems();
                }
            }
        }
    }

    public sealed class AnswerRow : Row, IIdRow, INameRow, IIsActiveDeletedRow, ILoggingRow, IDeleteLogRow
    {
        [DisplayName("Question Bank"), NotNull, ForeignKey("[dbo].[QuestionBank]", "Id"), LeftJoin("jQuestionBank"), TextualField("QuestionBankQuestionText"), LookupEditor(typeof(QuestionBankRow))]
        public Int32? QuestionBankId
        {
            get { return Fields.QuestionBankId[this]; }
            set { Fields.QuestionBankId[this] = value; }
        }

        [DisplayName("Answer Value"), Size(4000), NotNull, QuickSearch, AnswerValueEditor]
        public String AnswerValue
        {
            get { return Fields.AnswerValue[this]; }
            set { Fields.AnswerValue[this] = value; }
        }
    }

**Comment by volkanceylan** [comment]
Serenity developer guide daki cascaded dropdown how to sunu incelediniz mi?

**Comment by neonemivar** [comment]
Teşekkür ederim o yapıyı incelemiştim ama sanırım tanımlamaları hatalı yapmışım, biraz uğraşınca daha kolay bir biçimde çözüldü,
