### ISSUE TITLE
Kullanıcı bazlı filtreleme

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity-Tutorials#4]
Volkan bey,

Mevcut framework içerisinde verileri kullanıcılara yada kullanıcıların üye oldukları organizasyonlara göre filtrelemek için nasıl bir yöntem izlemem sizce uygundur. 

Her bir Repository içerisinde ki "private class MyListHandler : ListRequestHandler<MyRow> { }" u kullanarak yapmak mümkün, farklı daha az kodlama yapılarak çözüm üretilmesi mümkün müdür.

İlginiz ve desteğiniz için şimdiden teşekkür ederim.

**Comment by volkanceylan** [comment]
Sanırım Multi Tenant tutorial daki gibi birşey istiyorsunuz.

**Comment by neonemivar** [comment]
TenantId yapısına baktım, burada bir kullanıcı ilgili Row u sahipleniyor, mevcut yapıda UserGroup mantığı yok sanırım, ben bir grup Row un sahibi gibi hareket etsin istiyorum.
Yani Dekanlıklar var ve dekanlıklara bağlı personeller, personeller ile ilişkili kullanıcılar, her kullanıcı kendi dekanlığına bağlı verileri görüntüleyebilir. Birde sekreterler olsun bazı durumlarda bir den fazla dekanlık verilerine erişim sağlayacaklar.
Sanırım bu tarz bir durum için TenantId override edilemiyor ise ihtiyacı karşılamayacaktır. Row bazlı authorization yapısına ihtiyaç var gibi. Siz bu konuda ne düşünüyorsunuz.

**Comment by volkanceylan** [comment]
Bunun için kullanıcı ya da rol ile erişebilecekleri birimlerle ilgili bir tabloya ihtiyaç var. Oradaki bilgiyi EXISTS query si ile ListHandler ın ApplyFilters ını override ederek uygulayabilirsiniz. Biz böyle yapıyoruz.

**Comment by neonemivar** [comment]
Mevcut yapı içerisinde bende aynı mantık ile çözüm ürettim. Default query tarzında bir yapı kurgulanabilir ise her bir entity için ekstra bir kodlama maliyetine girilme zorunluluğu kalmadan sanırım daha hızlı ve kesin bir çözüm üretilmiş olabilir. B2B gibi yapılarda bayi kanalları için nerede ise tüm ListHandler override edilmek zorunda kalınacaktır. Lookup benzeri bir yapı ile ilişkili tablo ve column Row üzerinden atanarak ta yönetim kolaylaştırılabilir. Bir adım ötesi generate kısmı içinde gerekli geliştirmeler ile sanırım 0 efor ile bu gereksinim yönetilmiş olacaktır.

**Comment by volkanceylan** [comment]
Tüm ListHandler lar için yapmak yerine service behavior kullanabilirsiniz.
