### ISSUE TITLE
API service olarak kullanımı

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity-Tutorials#6]
Volkan bey,

Mevcut yapı içerisinde MVC Api desteği var mıdır. ServiceContracts.tt in ürettiği ve ServiceEndpoint den türemiş olan sınıflar API olarak kullanılabilir mi. API olarak kullanım esnasında Membership yönetimi, response ve request yapısı ile ilgili konularda örnek kodlar var ise paylaşabilir misiniz.

İlginiz ve desteğiniz için şimdiden teşekkür ederim.

**Comment by volkanceylan** [comment]
Web Api kullanmıyorum, pek incelemedim de, ama bildiğim kadarıyla MVC 5 te API ve normal controller ları birleştiriyorlar. Zaten gereksiz bir uygulama gibi gelmişti bana.

**Comment by neonemivar** [comment]
Web API mobile uygulama tarafında etkin olarak kullanılmakta, temelde json olarak veri taşındığı için yönetilmesi ve geliştirilmesi daha kolay. MVC 5 için mobile den erişimi bende denemedim, ancak geliştirdiği mobile application lar için Web API kullanıyorum. Şu an üzerinde çalıştığım proje için de MVC üzerinden erişimi (muhtemelen benden kaynaklıdır) sağlayamadığım için ayrı bir API controller yazdım. Mevcut sistem için bir mobile platform tasarımı yada örnek uygulama kodları mevcut mudur, bu tarz bir uygulama için nasıl bir yöntem önerirsiniz.

**Comment by volkanceylan** [comment]
ServiceEndpoint te JSON kullanıyor ve mobilden de erişilebiliyor. Sadece cookie desteği olan bir client kullanmanız lazım.

**Comment by neonemivar** [comment]
Volkan bey,
Paylaşabileceğiniz bir örnek uygulama yada proje var mıdır. Console application olarak ta olabilir, mobil bölümünü ben bir şekilde çözerim, login olunup her hangi bir entity üzerinde CRUD işlemlerinin yapılabiliyor olması benim açımdan yeterli.

**Comment by volkanceylan** [comment]
Şurada arkadaşların paylaştığı ufak bir gist var

https://gist.github.com/volkanceylan/1b124f58c1e2b4fc7c7c
