### ISSUE TITLE
Entity modele sahip olmayan bir page için yetkilendirme

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity-Tutorials#9]
Volkan bey,

Kendi tasarladığım bir cshtml form var, bu form için Page ve Endpoint controller lar oluşturdum, vs local debug da sorunsuz açılıyor ancak IIS üzerinde iken Windows Authentication istemekte, sizce nasıl bir çözüm üretebilirim, saygılarımla.

Modules/Reports/Test
TestReportsIndex.cshtml
TestReportsPage.cs
TestReportsEndpoint.cs

**Comment by volkanceylan** [comment]
Serenity de windows auth ile ilgili birşey yok normalde, IIS ayarlarında açılmış olabilir

**Comment by neonemivar** [comment]
Sanırım, tanımladığım page için authentication sağlayamadığı için windows yetkisi aramakta. IIS de klasör yetkilerini kontrol ettim, diğer ayarlarda da bir tanımlama farkı görünmüyor. Row üzerinde
    [ReadPermission("")]
    [ModifyPermission("")]
yetkileri var, bende Row mimarisi olmadığı için bir sorun mu oluşuyor, tabi bu durumda ulr Login e yönlenmeli... sorun konusunda şu an için bir fikir yürütemiyorum açıkcası.

**Comment by volkanceylan** [comment]
Bunlar sadece servis çağrımında kullanılır, boş bıraktığınız için giriş kontrolü yapılır. Siz windows auth istendiğini nereden anlıyorsunuz. Browser login popup ı çıkıyorsa site ayarlarından windows auth u kapatın.

**Comment by neonemivar** [comment]
Modules/Reports/Test yerine Modules/uReports/Test yaptım sorunsuz çalıştı, sanırım Reports için arka taraflarda bir tanımlama var...

**Comment by volkanceylan** [comment]
ReportController var ona düşüyordur.
